# Deploys QServ Integration GKE with Terraform
name: 'RSP DEV'

on:
  pull_request:
    paths:
      - 'environment/science-platform/env/dev.tfvars'
  push:
    branches:
      - main
    paths:
      - 'environment/science-platform/env/dev.tfvars'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./environment/science-platform

    # Checkout the repository to the GitHub Actions runner
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Installs terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.2.1

     # Initialize a new or existing terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init -backend-config=bucket=${{ secrets.TERRAFORM_STATE_BUCKET }} -backend-config=prefix=rsp/dev

    # Generates an execution plan for terraform
    - name: Terraform Plan
      id: plan
      run: terraform plan -var-file=env/dev.tfvars --var password=${{ secrets.DB_PASSWORD }}  -no-color

    # On push to main, build or change infrastructure according to terraform configuration files
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -var-file=env/dev.tfvars -refresh=false -auto-approve